### PR TITLE
Enhancement: Allow specifying the actual reference

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] allows specifying a `ref`

💁‍♂ We are using this action for a `pull_request` event, but we actually deploy a different reference than what would be the reference for the context - it would be nice if we could specify the actual reference here as well!

### CODE REVIEW

**Comment by chrnorm** [comment]
Thanks for the PR @localheinz! Adding these optional parameters is great as it makes the action work for different use cases (like yours).

It looks like the GitHub checks failed because `lib/main.js` hasn't been updated. I'll check out this branch and rebuild it. I'm still working on a better way to keep the built JS files up to date.

**Comment by localheinz** [comment]
@chrnorm 

I can highly recommend https://github.com/stefanzweifel/git-auto-commit-action - perhaps you can use it to compile, then commit and push back into the repository?

**Comment by chrnorm** [comment]
@localheinz thanks for the recommendation! I'll look at putting that on the master branch, so that future forks/PRs can benefit from it.

In the meantime I'll merge this and update `lib/main.js` directly on the `master` branch (looks like I can't directly commit to this PR). I'll cut a new release v1.2.0 today which will incorporate your changes too.

Thanks for the contribution!

**Comment by localheinz** [comment]
Thank you, @chrnorm!

**Pull request merged**
