### PR TITLE
Fix: Creating deployments for another repository fails with `Not Found`

### PR DESCRIPTION
**Pull request by liamoneill**
This PR fixes the action from failing when creating a deployment for another repo then where the workflow is running from.

Error from logs:
```
Error: HttpError: Not Found
Error: Error creating GitHub deployment: Not Found
```

This was caused by the `createDeploymentStatus` request hardcoding the repo & owner from  context instead of using the repo that deployment was created under.

I've tested the change in workflows that both create deployments on themselves and other repos and the fix applied to be working as expected.

### CODE REVIEW

**Comment by liamoneill** [comment]
Hey @chrnorm, thanks for your work on this action! Are you still accepting fixes? Would love to get this upstream if possible.

**Comment by chrnorm** [comment]
Hey @liamoneill - my apologies for the delay here. Thankyou so much for the fix!

**Comment by liamoneill** [comment]
> Hey @liamoneill - my apologies for the delay here. Thankyou so much for the fix!

No apology necessary! Thanks so much for the awesome work!

**Comment by chrnorm** [comment]
@liamoneill this has been released in [v2.0.4](https://github.com/chrnorm/deployment-action/releases/tag/v2.0.4) 😁

**Pull request merged**
